ibis:
- changed-files:
  - any-glob-to-any-file: ['ibis-server/**']

dependencies:
- changed-files:
  - any-glob-to-any-file: ['**/*.toml']

python:
- changed-files:
  - any-glob-to-any-file: ['ibis-server/**', 'analytics-core-py/**']

rust:
- changed-files:
  - any-glob-to-any-file: ['analytics-core/**']

core:
- changed-files:
  - any-glob-to-any-file: ['analytics-core/**']

documentation:
- changed-files:
  - any-glob-to-any-file: ['**/*.md']

bigquery:
- changed-files:
  - any-glob-to-any-file: ['**/*bigquery*']

ci:
- changed-files:
  - any-glob-to-any-file: ['.github/**']

v1-engine-changed:
- changed-files:
  - any-glob-to-any-file: ['analytics-base/**', 'analytics-main/**', 'analytics-server/**', 'analytics-tests/**', 'trino-parser/**', 'pom.xml']
